### ISSUE TITLE
Decide on a service to migrate the HOF images and CuratorBot

### ISSUE THREAD

**Issue by originalnicodr** [framedsc/HallOfFramed#33]
We need to decide on the service that we will be using for hosting the pics and the bot. Here are some alternatives that have been thrown into the discussion:

- [Cloudfire](https://developers.cloudflare.com/images/cloudflare-images/)
- [WebDockl](https://webdock.io/en/about-us)

Alternatively, Frans has [Azure](https://azure.microsoft.com/es-es) credits so we could use that, but I would like to weigh our options first. I wouldn't want to go for Azure just because it's "free" for us, especially knowing how much it normally costs.

Regarding the variables that need to be taken into account for this, I am thinking of the following ones:
- Price
- Space
- CPU power
- Image loading speed

Space is particularly important given how much storage space the images are currently costing. See #26.

**Comment by originalnicodr** [comment]
Frans mentioned these two options as well:

- [imgix](https://imgix.com/pricing)
- [sirv](https://sirv.com/pricing/)

**Comment by etra0** [comment]
I made a (bit) rough estimate, and with 200gb of storage we should be fine for almost 5 years.

**Comment by FransBouma** [comment]
Sounds great. I don't think we should calculate in bigger storage. If it comes to that we can deal with it then I guess :)

**Comment by originalnicodr** [comment]
It's good to have an estimation, but maybe it makes sense to start with less storage and start increasing the hosting when we need it (I guess whatever VM we hire would notify us of that). Besides, maybe we can optimize it some more with #26.

Having said that, maybe prioritizing a host that has reasonable prices for increased storage should be the priority.

**Comment by originalnicodr** [comment]
We decided to go with Backblaze and Cloudflare. Using both should cost us around $6/m, since Backblaze hosting costs us 6 USD per TB, and the network usage on Cloudflare is free with Backblaze (101GB max total per day I believe, don't quote me on that).
